# Make sure to accept the license agreement on huggingface hub
text_model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
audio_model: "openai/whisper-small"


loss_config:
  # Choose from ["KL_Divergence", "CrossEntropy"], default is "KL_Divergence"
  loss_function: "KL_Divergence"

# Temporarily remove heysquad_human from val_sets as it causes the training to fail.
val_sets: ["anyinstruct", "soda", "peoplespeech"]

batch_size: 24
max_steps: 7200 # x8x24 = 2,764,800
data_sets: []
data_dicts:
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100" # 28_539 samples
      - "train.360" # 104_014 samples
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
    weight: 1
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500" # 148_688 samples
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
    weight: 1
  - path: "fixie-ai/common_voice_17_0"
    name: "en"
    splits:
      - "train" # 1_101_170 samples
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text_proc.format_asr_text(sentence) }}"
    weight: 8
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100" # 28_539 samples
      - "train.360" # 104_014 samples
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text }}"
    transcript_template: "{{ text }}"
    weight: 1
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500" # 148_688 samples
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text }}"
    transcript_template: "{{ text }}"
    weight: 1
  - path: "fixie-ai/common_voice_17_0"
    name: "en"
    splits:
      - "train" # 1_101_170 samples
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(sentence) }}"
    transcript_template: "{{ text_proc.format_asr_text(sentence) }}"
    weight: 8
