# SLM with ultravox & llama3, trained wtih knowledge distillation.
exp_name: "zhuang.2024-07-31-ultravox.blsp-kd-2-tinyllama"

# Make sure to accept the license agreement on huggingface hub
text_model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
audio_model: "openai/whisper-small"


loss_config:
  # Choose from ["KL_Divergence", "CrossEntropy"], default is "KL_Divergence"
  loss_function: "KL_Divergence"

# Temporarily remove heysquad_human from val_sets as it causes the training to fail.
val_sets: ["anyinstruct", "soda", "peoplespeech"]

batch_size: 4
max_steps: 4000

data_sets: []
data_dicts:
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100"
      - "train.360"
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
    # num_samples: 100_000
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500"
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
    # num_samples: 100_000
