exp_name: "zhuang.2024-07-15-ultravox.blsp-kd-4a"

# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
audio_model: "openai/whisper-small"

batch_size: 24
max_steps: 2000 
# librispeech:  281,241
# gigaspeech: 1,101,170
# anyinstruct:  105,704
# boolq_extended: 9,427   # it should not be used because the binary answer provides very little supervsion
# soda: 100,000

device: "cuda"

loss_config:
  loss_function: "KL_Divergence"

# data_sets: ["gigaspeech", "anyinstruct", "boolq_extended", "soda"]
data_sets: []

report_logs_to: ["tensorboard", "wandb"]

num_prompts: 100 # a sufficient number of prompts to cover all prompts

data_dicts:
  - path: "speechcolab/gigaspeech"
    name: "xl"
    splits:
      - "train"
    user_template: "{{ dataset._get_transcribe_prompt() }}"
    assistant_template: "{{ text_proc.format_asr_text(text) }}"
    transcript_template: "{{ text_proc.format_asr_text(text) }}"
    num_samples: 100_000
    weight: 1
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100"
      - "train.360"
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
    weight: 5
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500"
    weight: 4
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
