exp_name: "zhuang.2024-07-15-ultravox.blsp-3"

# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Meta-Llama-3-8B-Instruct"
audio_model: "openai/whisper-small"


max_steps: 976 # 281,241 / 36 / 8 

data_sets: []

device: "cuda"

batch_size: 36

report_logs_to: ["tensorboard", "wandb"]

data_dicts:
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100"
      - "train.360"
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500"
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"