exp_name: "zhuang.2024-07-15-ultravox.ultravox-0.2-llama3.1"

# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
audio_model: "openai/whisper-small"

model_load_dir: "wandb://fixie/ultravox/model-llama3.1_whisper_s__gs__gs_ai_bqx_soda:v1"

max_steps: 1464  # 281,241 / 24 / 8 

data_sets: []

do_train: False

device: "cuda"

batch_size: 24

  
report_logs_to: ["tensorboard", "wandb"]